# Generated by Django 5.2.11 on 2026-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('created_AT', models.DateField(auto_now=True)),
                ('isPublish', models.BooleanField(default=True)),
            ],
        ),
    ]
